# Generated by Django 4.1.7 on 2023-04-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vastaus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimimerkki', models.CharField(max_length=100)),
                ('tyytyvaisyys', models.IntegerField(blank=True, null=True)),
                ('stressi', models.IntegerField(blank=True, null=True)),
                ('ahdistus', models.IntegerField(blank=True, null=True)),
                ('esimiestuki', models.IntegerField(blank=True, null=True)),
                ('tyokaverituki', models.IntegerField(blank=True, null=True)),
                ('tunnustus', models.IntegerField(blank=True, null=True)),
                ('yhteiso', models.IntegerField(blank=True, null=True)),
                ('ilo', models.IntegerField(blank=True, null=True)),
                ('palaute', models.TextField(blank=True)),
            ],
        ),
    ]
